[package]
name = "esdt-safe-meta"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.esdt-safe]
path = ".."

[dependencies.elrond-wasm]
version = "0.32.0"

[dependencies.elrond-wasm-debug]
version = "0.32.0"
