[package]
name = "esdt-safe-meta"
version = "0.0.0"
authors = ["you"]
edition = "2018"
publish = false

[dev-dependencies]

[dependencies.esdt-safe]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.50.4"
default-features = false
