[workspace]
members = [
  "egld-esdt-swap",
  "egld-esdt-swap/meta",
  "esdt-safe",
  "esdt-safe/meta",
  "multi-transfer-esdt",
  "multi-transfer-esdt/meta",
  "multisig",
  "multisig/meta",
  "price-aggregator",
]
