[package]
name = "max-bridged-amount-module"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@elrond.com>",]
edition = "2018"

[dependencies.elrond-wasm]
version = "0.32.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.32.0"
