[package]
name = "wrapped-bridged-usdc"
version = "0.0.0"
authors = ["Alin Cruceat <alin.cruceat@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.29.3"

[dev-dependencies.elrond-wasm-debug]
version = "0.29.3"
