[package]
name = "token-module"
version = "0.0.0"
authors = [ "dorin-iancu <dorin.iancu@elrond.com>",]
edition = "2018"

[features]
wasm-output-mode = ["elrond-wasm-node"]

[dependencies.fee-estimator-module]
path = "../fee-estimator-module"

[dependencies.elrond-wasm]
version = "0.17.4"

[dependencies.elrond-wasm-derive]
version = "0.17.4"

[dependencies.elrond-wasm-node]
version = "0.17.4"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.17.4"
